version: "3"

volumes:
  postgres_data: {}

services:
  postgres:
    image: postgres:15.2-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
